name: 'Go License Checker'
author: 'yusufpapurcu'
description: 'Check licenses in your go package'

inputs:
  runVendor:
    description: "If set false, action won't do `go mod vendor`"
    default: true

branding:
  icon: file-text
  color: green
runs:
  using: "composite"
  steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.22
      id: go

    - run: |
        if echo ${{ inputs.runVendor }} | grep -c "true"
          then
            go mod vendor
          else
            echo "Skipping Vendoring Step"          
          fi
      shell: bash

    - name: Run go mod vendor
      if: inputs.runVendor == 'true'
      run: go mod vendor
      shell: bash

    - name: Get google/go-licenses package
      run: go install github.com/google/go-licenses@latest
      shell: bash

    - name: Run Check
      run: ${{ github.action_path }}/check.sh
      shell: bash

    - name: Get them as csv
      run: go-licenses csv .
      shell: bash
